### ISSUE TITLE
GetUserPhoto request

### ISSUE THREAD

**Issue by isakar** [nmarus/node-ews#10]
Hi! I am using your module and this time I want to get the photo: https://msdn.microsoft.com/en-us/library/office/jj190905(v=exchg.150).aspx but I see 2 things, in your api, I need to set the functions and the other is something in the structure, your body request is built like:

`<soap:Body>
<GetUserPhoto xmlns="http://schemas.microsoft.com/exchange/services/2006/messages">
    <GetUserPhoto>
        <Email>userEmail@email.com</Email>
        <SizeRequested>HR360x360</SizeRequested>
  </GetUserPhoto>
 </GetUserPhoto></soap:Body></soap:Envelope>`

the way to build it is like:

```
<soap:Body>
<m:GetUserPhoto>
<m:Email>userEmail@email.com</m:Email>
<m:SizeRequested>HR360x360</m:SizeRequested>
</m:GetUserPhoto></soap:Body></soap:Envelope>
```
 
I did a little hack to change it but I get an error: ERROR: Error: Cannot parse response

Do you think is there any chance to retrieve it?

Thanks!

**Comment by jontowles** [comment]
Beyond that any Soap request should be in the m: format and not just straight XML.

**Comment by nmarus** [comment]
Please try the 2.0.0-dev branch and see if that resolves issues. Note this is a major rewrite and some command syntax is different.
