### ISSUE TITLE
Lib doesn't work when I disable NTLM and try request

### ISSUE THREAD

**Issue by ervinfetic** [nmarus/node-ews#11]
In my case where I have two type of auth (basic and ntlm) I did disable NTLM then tried to use this lib and I got this error below:

![terminal_ _mongod_ _sudo_ _224x24](https://cloud.githubusercontent.com/assets/15788855/15969282/a9561c34-2f2f-11e6-931a-d53015e7f1d2.jpg)

**Comment by nmarus** [comment]
The package currently forces NTLM authentication. If you are looking for similar functionality, check out https://www.npmjs.com/package/soap which this package is uses along with a customized authentication module and some post processing.
