### ISSUE TITLE
"Unexpected root element of WSDL or include"

### ISSUE THREAD

**Issue by tdhulster** [nmarus/node-ews#12]
I keep getting this error - "Unexpected root element of WSDL or include" - when trying to create soap client, but I have no idea where I have to start looking to resolve this;

The response is gzipped though so I tried to add "wsdl_options: { gzip: true }" to the soap createClient options object without any luck.
http://stackoverflow.com/questions/30139878/how-to-consume-wcf-in-node-js

Any idea what I can check/change to resolve this?

**Comment by regimbal93** [comment]
I removed his wsdlFix variable from the file ews.js on line 137 which seemed to fix that error... but then you get "Cannot set property 'descriptions' of null" ... can the author provide guidance?

**Comment by nmarus** [comment]
Please try the 2.0.0-dev branch and see if that resolves issues. Note this is a major rewrite and some command syntax is different.

**Comment by jontowles** [comment]
I'm seeing the same issue with getting out of office.

Do you think 2.0.0 will address that? When do you expect 2.0.0 to be prod?

**Comment by isakar** [comment]
Hi,
I was testing the 2.0.0-dev branch and I did the changes for the auth config, but now I just get this error:

`Potentially unhandled rejection [1] Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)`

If there is some config that I am missing for that branch?

Thanks

**Comment by isakar** [comment]
Ok, seems that my eclipse was doing something bad.. I don't have the timeouts anymore but then I get this:

`Potentially unhandled rejection [1] Unexpected root element of WSDL or include (WARNING: non-Error used)`

**Comment by kcastrotech** [comment]
When I was getting this error it was due to bad credentials which resulted in an empty wsdl.

I discovered this by adding some console.logs to the getFile function in the init section of the ews.js file:
 ```
 // get file via ntlm
  function getFile(url, file) {
	console.log("Getting file with NTLM:",url + " => "+file);
    ntlmOptions.url = url;
    return when.promise((resolve, reject) => {
      ntlm.get(ntlmOptions, function (err, res) {
        if(err) reject(err);
        else {
		  console.log("NTLM Response:",res.statusCode);
          fs.writeFile(file, res.body, function(err) {
            if(err) reject(err);
            else resolve(file);
          });
        }
      });
    });
  }
```

Because it is unable to retrieve the file, the init script is simply appending the wdsl fix contents to an empty string which of course results in a malformed wdsl file.

I updated the getFile function to reject if the NTLM response code is 401 (unauthorized):
 ```
 // get file via ntlm
  function getFile(url, file) {
	console.log("Getting file with NTLM:",url + " => "+file);
    ntlmOptions.url = url;
    return when.promise((resolve, reject) => {
      ntlm.get(ntlmOptions, function (err, res) {
        if(err) reject(err);
        else {
		  if(res.statusCode==401) reject('NTLM StatusCode 401: Unauthorized.');
          fs.writeFile(file, res.body, function(err) {
            if(err) reject(err);
            else resolve(file);
          });
        }
      });
    });
  }
```

And added a check for the presence of an opening wsdl ('<wsdl:definitions') in the readFile of the init's return promise and if it doesn't exist then it will reject it:
```
      // fix ms wdsl...
      // https://msdn.microsoft.com/en-us/library/office/aa580675.aspx
      // The EWS WSDL file, services.wsdl, does not fully conform to the WSDL standard
      // because it does not include a WSDL service definition. This is because EWS is
      // not designed to be hosted on a computer that has a predefined address.
      return when.promise((resolve, reject) => {
        fs.readFile(file, 'utf8', function(err, wsdl) {
		  if(wsdl.search('<wsdl:definitions')==-1) reject('Invalid or malformed wsdl file.\nFile: '+file);
          if(err) reject(err);
          else {
            // break file into an array of lines
            var wsdlLines = wsdl.split('\n');
            // remove last 2 elements of array
            wsdlLines.splice(-2,2);
            // join the array back into a single string and apply fix
            var newWsdl = wsdlLines.join('\n') + wsdlFix;
            // write file back to disk
            fs.writeFile(file, newWsdl, function(err) {
              if(err) reject(err);
              else resolve(file);
            });
          }
        });
      })
```

**Comment by nmarus** [comment]
Thanks! I will review and look to roll this into the next patch.

**Comment by nmarus** [comment]
Please try the 2.1.0-dev branch. This includes the additional error notifications suggested above by @kcastrotech
