### ISSUE TITLE
invalid child element 'Contains' in namespace 'http://schemas.microsoft.com/exchange/services/2006/messages'."

### ISSUE THREAD

**Issue by juan-ruiz** [nmarus/node-ews#18]
Hey-oh guys!

Im trying to retrieve all the mails from my mailbox that contain CSAT on the subject,

Now, i am getting the following error:

"a:ErrorSchemaValidation: The request failed schema validation: The element 'FindItem' in namespace 'http://schemas.microsoft.com/exchange/services/2006/messages' has invalid child element 'Contains' in namespace 'http://schemas.microsoft.com/exchange/services/2006/messages'."

Here is my code:

```
var ewsFunction = 'FindItem';
var ewsArgs = {
    attributes: {
        Traversal: 'Shallow'
    },
    ItemShape: {
        BaseShape: 'IdOnly',
        AdditionalProperties: {
            FieldURI: {
                attributes: {
                    FieldURI: 'item:Subject'
                }
            }
        }
    },
    ParentFolderIds: {
        DistinguishedFolderId: {
            attributes: {
                Id: 'inbox'
            }
        }
    },
    Contains: {
      attributes: {
        ContainmentMode: 'Substring',
        ContainmentComparison: 'IgnoreCase'
      },
      FieldURI: {
          attributes: {
              FieldURI: 'item:Subject'
          }
      },
      Constant: {
          attributes: {
              Value: 'CSAT'
          }
      }
    },
    headers: {
        'http://schemas.microsoft.com/exchange/services/2010/types': [{
            RequestServerVersion: {
                attributes: {
                    Version: 'Exchange2010'
                }
            }
        }]
    }
};
```

Now, i think this issue is related to the versioning of the request, but, it doesn't matter what i put  on the headers field, i always get the same error.

Now, do you know how to perform this search correctly?

**Comment by nmarus** [comment]
Please refer to this on the valid child elements of "FindItem"  https://msdn.microsoft.com/en-us/library/office/aa566370.aspx

You are probably looking for "QueryString" child element https://msdn.microsoft.com/en-us/library/office/ee693615.aspx

**Comment by juan-ruiz** [comment]
Im getting the following

"a:ErrorSchemaValidation: The request failed schema validation: The element 'FindItem' in namespace 'http://schemas.microsoft.com/exchange/services/2006/messages' has invalid child element 'QueryString' in namespace 'http://schemas.microsoft.com/exchange/services/2006/messages'."

again, im using also the following snippet

    headers: {
        'http://schemas.microsoft.com/exchange/services/2010/types': [{
            RequestServerVersion: {
                attributes: {
                    Version: 'Exchange2010'
                }
            }
        }]
    }

but i still get the 2006 error, also, im pretty sure the server is an exchange server 2010,

Best Regards,

**Comment by nmarus** [comment]
A schema validation error means you are using a property that does not exist in the schema. I would suggest dropping the headers section (and you have it as a child of FindItem which it is not anyway, and neither is "Contains") as that is not needed if you are using node-ews. It takes care of the schema through the wsdl file it gets from the ews api and all you need to worry about is the SOAP body. 

For example, this SOAP query to search for messages with "Autodiscover" in the subject. 
https://msdn.microsoft.com/en-us/library/office/ee693615(v=exchg.140).aspx

```xml
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" 
               xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" 
               xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header>
    <t:RequestServerVersion Version="Exchange2010" />
  </soap:Header>
  <soap:Body>
    <m:FindItem Traversal="Shallow">
      <m:ItemShape>
        <t:BaseShape>IdOnly</t:BaseShape>
        <t:AdditionalProperties>
          <t:FieldURI FieldURI="item:Subject" />
        </t:AdditionalProperties>
      </m:ItemShape>
      <m:IndexedPageItemView MaxEntriesReturned="1" Offset="0" BasePoint="Beginning" />
      <m:ParentFolderIds>
        <t:DistinguishedFolderId Id="inbox" />
      </m:ParentFolderIds>
      <m:QueryString>subject:Autodiscover</m:QueryString>
    </m:FindItem>
  </soap:Body>
</soap:Envelope>
```

Should look like:

```json
{
  "attributes": {
    "Traversal": "Shallow"
  },
  "ItemShape": {
    "BaseShape": "IdOnly",
    "AdditionalProperties": {
      "FieldURI": {
        "attributes": {
          "FieldURI": "item:Subject"
        }
      }
    }
  },
  "IndexedPageItemView": {
    "attributes": {
      "MaxEntriesReturned": "1",
      "Offset": "0", 
      "BasePoint": "Beginning"
    }
  },
  "ParentFolderIds": {
    "DistinguishedFolderId": {
      "attributes": {
        "Id": "inbox"
      }
    }
  },
  "QueryString": "subject:Autodiscover"
}
```

**Comment by kcastrotech** [comment]
I've also seen this error to where it said the child was unexpected and then listed acceptable child elements including the one that it complained about not being valid. What I discovered is that for some reason on the soap envelope it wasn't always adding the 't:' prefix for child types or 'm:' for prefix for messages.

I haven't figured out why yet, but to get around the issue, if it still gives the error try this:
```
var ewsArgs = {
  "attributes": {
    "Traversal": "Shallow"
  },
  "ItemShape": {
    "BaseShape": "IdOnly",
    "AdditionalProperties": {
      "FieldURI": {
        "attributes": {
          "FieldURI": "item:Subject"
        }
      }
    }
  },
  "ParentFolderIds": {
    "DistinguishedFolderId": {
      "attributes": {
        "Id": "inbox"
      }
    }
  },
  "m:QueryString": "subject:CSAT"
}
```

**Comment by juan-ruiz** [comment]
@kcastrotech  i tried your solution, nonetheless i am getting 

"a:ErrorSchemaValidation: The request failed schema validation: 'm' is an undeclared namespace. Line 1, position 968."

You mentioned you saw discover an issue with the soap envelop, now, how did you do it? is there any way you can see the resulting soap xml that is sent to the server? (since the communication is encrypted i cant use a sniffer)

**Comment by kcastrotech** [comment]
So the "m:" prefix matches the 

> xmlns:**m**="http://schemas.microsoft.com/exchange/services/2006/messages"

line in nmarus' example:
```
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" 
               xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" 
               xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
```

However, in my system it seems to be using "tns:" for the messages:

> xmlns:**tns**="http://schemas.microsoft.com/exchange/services/2006/messages"

 so you might try "tns:QueryString" instead of "m:QueryString".

And to debug the actual XML envelope you will need to edit the client.js file in the soap library which is likely to be found either at

> \node_modules\node-ews\node_modules\soap\lib

or

> \node_modules\soap\lib

Simply add 
`console.log("XML:",xml);`

to line 241 which should look like this:
```
xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?>" +
    "<soap:Envelope " +
    xmlnsSoap + " " +
    "xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" " +
    encoding +
    this.wsdl.xmlnsInEnvelope + '>' +
    ((self.soapHeaders || self.security) ?
      (
        "<soap:Header>" +
        (self.soapHeaders ? self.soapHeaders.join("\n") : "") +
        (self.security ? self.security.toXML() : "") +
        "</soap:Header>"
      )
      :
        ''
      ) +
    "<soap:Body" +
    (self.bodyAttributes ? self.bodyAttributes.join(' ') : '') +
    ">" +
    message +
    "</soap:Body>" +
    "</soap:Envelope>";
console.log("XML:",xml);
  self.lastMessage = message;
  self.lastRequest = xml;
  self.lastEndpoint = location;
```

This will output the actual XML message before sending it to the server.

**Comment by kcastrotech** [comment]
In my situation it does appear to be a namespace issue in resolving the types for the ews MoveItem operation. After debugging and digging around it would seem the node-soap guys are aware that there are sometimes issues with namespace resolution and provided exactly this workaround:
https://github.com/vpulim/node-soap#overriding-the-namespace-prefix

**Comment by juan-ruiz** [comment]
ok here is what i have till now:

```
{
    "attributes": {
    "Traversal": "Shallow"
  },
  "ItemShape": {
    "BaseShape": "IdOnly",
    "AdditionalProperties": {
      "FieldURI": {
        "attributes": {
          "FieldURI": "item:Subject"
        }
      }
    }
  },
  "ParentFolderIds": {
    "DistinguishedFolderId": {
      "attributes": {
        "Id": "inbox"
      }
    }
  },
  "tns:QueryString": "subject:CSAT"
};
```

here is what im getting:

"a:ErrorIncorrectSchemaVersion: The request is valid but does not specify the correct server version in the RequestServerVersion SOAP header. Ensure that the RequestServerVersion SOAP header is set with the correct RequestServerVersionValue."

I try adding the header tag again  but i get back to the invalid child element Querystring,

Again, thank you guys for all the help!

**Comment by kcastrotech** [comment]
It sounds like the RequestServerVersion header is required for FindItem when you are using QueryString. Try adding the header by editing the ews.js file (\node_modules\node-ews\lib\ews.js)  and adding a line for client.addSoapHeader(...) just after the security plugin section, like this:
```
          // define security plugin
          client.setSecurity(authProfile);
		  client.addSoapHeader({'t:RequestServerVersion': {
			attributes: {
				Version: "Exchange2013"
			}
		  }});
```

**Comment by juan-ruiz** [comment]
Hi there, im a little bit lost in here,

what does setSecurity do? and what is authprofile? 

since i just pasted the code as you delivered im getting this on the console:

C:\Users\ruizvilla\workspace.DEV\persoMachine\node_modules\node-ews\lib\ews.js:127 Uncaught ReferenceError: authProfile is not defined

Im must be doing something wrong but i just dont know where,

BR,

**Comment by kcastrotech** [comment]
Only the "client.AddSoapHeader(..." part should have been pasted. The "client.setSecurity(..." part was an original part of node-ews and was included for refference as to what to look for in the file and should be able to be found on line 218. Based on the error, it looks like you pasted it on line 127. However, with the new version posted today, nmarus has added the ability to add optional headers so you don't need to edit the ews.js file.

Please update your node-ews installation by running "npm install node-ews" again and follow the example in the readme file for how to use it.

**Comment by juan-ruiz** [comment]
It finally worked, maybe i can put my implementation as an example for the readme, i know it would've helped me a lot :)

**Comment by nmarus** [comment]
@juan-ruiz Definitely. Either post it here and Ill get it added or send it to my email at nmarus@gmail.com.

**Comment by qimuxi1990** [comment]
Hi,
I read through the configuration and this issue thread but met with an issue when creating contact with Notes field.
When I did not specify the server version, or specified the version to Exchange2010, it reported error:  `The request is valid but does not specify the correct server version in the RequestServerVersion SOAP header.  Ensure that the RequestServerVersion SOAP header is set with the correct RequestServerVersionValue.`
When I specified the version to Exchange2013, it reported error: `ErrorInvalidServerVersion: The specified server version is invalid.`
Anyone has an idea of what is happening?
[EWS Contact Module for Exchange 2010](https://msdn.microsoft.com/en-us/library/office/aa581315(v=exchg.140).aspx)
And here is my server information:
```
Edition             : Standard
AdminDisplayVersion : Version 14.3 (Build 123.4)
ExchangeVersion     : 0.1 (8.0.535.0)
```
And my args
```json
{
  "SavedItemFolderId": {
    "DistinguishedFolderId": {
      "attributes": {
        "Id": "contacts"
      }
    }
  },
  "Items": {
    "Contact": {
      "FileAs": "Ews M Tester",
      "GivenName": "Ews",
      "MiddleName": "M",
      "CompanyName": "A CompanyName",
      "PhysicalAddresses": {
        "Entry": [
          {
            "attributes": {
              "Key": "Business"
            },
            "CountryOrRegion": "United States"
          },
          {
            "attributes": {
              "Key": "Other"
            },
            "Street": "123 Street",
            "CountryOrRegion": "RegionA"
          }
        ]
      },
      "PhoneNumbers": {
        "Entry": [
          {
            "$value": "+1 xxx-xxx-xxxx",
            "attributes": {
              "Key": "BusinessPhone"
            }
          },
          {
            "$value": "+1 xxx-xxx-xxxx",
            "attributes": {
              "Key": "BusinessPhone2"
            }
          },
          {
            "$value": "+1 xxx-xxx-xxxx",
            "attributes": {
              "Key": "MobilePhone"
            }
          }
        ]
      },
      "JobTitle": "Ews Tester",
      "Surname": "Tester",
      "Notes": "Some Notes"
    }
  }
}
```
