### ISSUE TITLE
Allow disabling of SSL checking

### ISSUE THREAD

**Issue by r24y** [nmarus/node-ews#2]
I work on a corporate intranet with self-signed certs, and I imagine this is a moderately common scenario.

I'd be willing to work on this; I just wanted to set up an issue first so if anyone else is interested then we can coordinate efforts.

**Comment by nmarus** [comment]
Thanks for the offer. Feel free to work on it. I think it is related to the soap package which would be changed via this setting: https://www.npmjs.com/package/soap#clientsslsecurity

Though, it could be ntlm since I am over-riding the http client of the soap package.

**Comment by nmarus** [comment]
Replaced httpntlm with a modified fork of request-ntlm and added functionality to config to allow connections to self signed SSL.
