### ISSUE TITLE
Request for Feedback: Authentication methods available to node-ews

### ISSUE THREAD

**Issue by nmarus** [nmarus/node-ews#20]
The latest version of node-ews has updates that make adding an alternative authentication method more modular. At the moment only NTLM is supported but there seem to be some open issues (ie #15) that I suspect are related to many implementations using basic-auth. While [MS is saying that basic auth is not recommended](https://msdn.microsoft.com/en-us/library/office/dn626019%28v=exchg.150%29.aspx), the reality is that this is not the case. 

1) I'm curious to know how many are running into issues because of basic auth limits in node-ews? 

2) Also, I'm looking for anyone that has access to a basic auth EWS setup that would be willing to create a test account for me to test/validate the basic auth mode that I am working on. This is currently implemented in the dev branch, but I have yet to test this and simply going on how other basic auth integrations I have built to other API services. Please message me at nmarus@gmail.com if this is something you can provide. This may prove faster than me spinning up a lab Exchange server with basic auth on the EWS service.

**Comment by nmarus** [comment]
#15

**Comment by ng-marcus** [comment]
I'd like to have basic auth added because as far as I can tell Office 365 doesn't support NTLM authentication.

**Comment by eino-makitalo** [comment]
Yes Office 365 supports only Basic auth and oauth

**Comment by nmarus** [comment]
Thanks for the feedback. Basic auth and Office 365 support with examples incoming.

**Comment by nmarus** [comment]
Features for Basic Auth is now in version v3.0.0
