### ISSUE TITLE
initFiles doesn't set tempDir if ifDirExists fails

### ISSUE THREAD

**Issue by aderbedr** [nmarus/node-ews#29]
If ifDirExists fails and it gets to the catch block, "this" is undefined, which then it goes to set tempDir of undefined and fails. You cannot access "this" inside a promise block to my knowledge.

**Comment by nmarus** [comment]
Glanced at code. The usage if "this" when using arrow functions changes the behavior of "this" and is no longer relative to the interior block. Will test to see where issue may be and get back.

**Comment by nmarus** [comment]
I have a fix implemented/tested. Patch incoming.

**Comment by nmarus** [comment]
Resolved in version v3.0.0
