### ISSUE TITLE
GetUserAvailability issue

### ISSUE THREAD

**Issue by isakar** [nmarus/node-ews#3]
I am so glad to found your plug-in, actually it's the only one in which I can do calls to the EWS functions. Hoping you can help me cause I am trying to get the user availability and I get a request, but I think in some point the data is missing, I mean, the start and end time in the response I am seeing in StartTime and EndTime is always '00' 

This is an example of the response:

`{"Envelope":{"$":{"xmlns:s":"//schemas.xmlsoap.org/soap/envelope/"},"Header":[{"ServerVersionInfo":[{"$":{"MajorVersion":"15","MinorVersion":"0","MajorBuildNumber":"1156","MinorBuildNumber":"2","xmlns:h":"//schemas.microsoft.com/exchange/services/2006/types","xmlns":"//schemas.microsoft.com/exchange/services/2006/types","xmlns:xsd":"//www.w3.org/2001/XMLSchema","xmlns:xsi":"//www.w3.org/2001/XMLSchema-instance"}}]}],"Body":[{"$":{"xmlns:xsi":"//www.w3.org/2001/XMLSchema-instance","xmlns:xsd":"//www.w3.org/2001/XMLSchema"},"GetUserAvailabilityResponse":[{"$":{"xmlns":"//schemas.microsoft.com/exchange/services/2006/messages"},"FreeBusyResponseArray":[{"FreeBusyResponse":[{"ResponseMessage":[{"$":{"ResponseClass":"Success"},"ResponseCode":["NoError"]}],"FreeBusyView":[{"FreeBusyViewType":[{"_":"FreeBusy","$":{"xmlns":"//schemas.microsoft.com/exchange/services/2006/types"}}],"CalendarEventArray":[{"$":{"xmlns":"//schemas.microsoft.com/exchange/services/2006/types"},"CalendarEvent":[{"StartTime":["00"],"EndTime":["00"],"BusyType":["Busy"]},{"StartTime":["00"],"EndTime":["00"],"BusyType":["Busy"]},{"StartTime":["00"],"EndTime":["00"],"BusyType":["Busy"]},{"StartTime":["00"],"EndTime":["00"],"BusyType":["Busy"]},{"StartTime":["00"],"EndTime":["00"],"BusyType":["Tentative"]},{"StartTime":["00"],"EndTime":["00"],"BusyType":["Busy"]},{"StartTime":["00"],"EndTime":["00"],"BusyType":["Busy"]},{"StartTime":["00"],"EndTime":["00"],"BusyType":["Busy"]},{"StartTime":["00"],"EndTime":["00"],"BusyType":["OOF"]},{"StartTime":["00"],"EndTime":["00"],"BusyType":["Busy"]},{"StartTime":["00"],"EndTime":["00"],"BusyType":["Busy"]},{"StartTime":["00"],"EndTime":["00"],"BusyType":["Busy"]},{"StartTime":["00"],"EndTime":["00"],"BusyType":["Busy"]},{"StartTime":["00"],"EndTime":["00"],"BusyType":["Busy"]},{"StartTime":["00"],"EndTime":["00"],"BusyType":["Busy"]},{"StartTime":["00"],"EndTime":["00"],"BusyType":["Tentative"]},{"StartTime":["00"],"EndTime":["00"],"BusyType":["Busy"]},{"StartTime":["00"],"EndTime":["00"],"BusyType":["Busy"]},{"StartTime":["00"],"EndTime":["00"],"BusyType":["Tentative"]}]}],"WorkingHours":[{"$":{"xmlns":"//schemas.microsoft.com/exchange/services/2006/types"},"TimeZone":[{"Bias":["300"],"StandardTime":[{"Bias":["0"],"Time":["00"],"DayOrder":["1"],"Month":["11"],"DayOfWeek":["Sunday"]}],"DaylightTime":[{"Bias":["-60"],"Time":["00"],"DayOrder":["2"],"Month":["3"],"DayOfWeek":["Sunday"]}]}],"WorkingPeriodArray":[{"WorkingPeriod":[{"DayOfWeek":["Monday Tuesday Wednesday Thursday Friday"],"StartTimeInMinutes":["480"],"EndTimeInMinutes":["1020"]}]}]}]}]}]}]}]}]}}`

And the args i am building to get it:
var ewsAvailFunction = 'GetUserAvailability';
var ewsAvail = {
   'TimeZone':{
      'Bias' : '480',
      'StandardTime':{
         'Bias':'0',
         'Time':'02:00:00',
         'DayOrder':'5',
         'Month':'10',
         'DayOfWeek':'Sunday'
      },
      'DaylightTime':{
         'Bias':'300',
         'Time':'02:00:00',
         'DayOrder':'1',
         'Month':'4',
         'DayOfWeek':'Sunday'
      }
   },
   'MailboxDataArray':{
      'MailboxData':{
         'Email':{
            'Name':'',
            'Address': 'isakargarcia@consultantemail.com',
            'RoutingType':'SMTP'
         },
         'AttendeeType':'Organizer',
         'ExcludeConflicts':'false'
      }
   },
   'FreeBusyViewOptions':{
      'TimeWindow':{
         'StartTime':'2016-03-31T00:00:00',
         'EndTime':'2016-04-02T00:00:00'
      },
      'MergedFreeBusyIntervalInMinutes':'30',
      'RequestedView':'FreeBusy'
   }
};

Please, let me know any thought!

**Comment by nmarus** [comment]
node-ews is returning the raw xml response  parsed through xml2js package. It appears the xml2js dependency is not processing the timestamp data in the xml reply correctly.

**Comment by isakar** [comment]
Oh, I see.. thank you for the information, I hope they would fix it soon.

**Comment by nmarus** [comment]
I need to verify still. Currently this is only speculation until I have a chance to review in more depth. If you have the ability, you can disable the xml2json parser and see if the raw xml response includes the timestamps correctly.

**Comment by isakar** [comment]
Hi, i just checked the response from your ews.js and the timestamps are fine, so probably your theory it's correct and the xml2json could be processing the timestamp incorrectly.

**Comment by FiveOneDigital** [comment]
Hey, I had a similar issue. xml2js is definitely processing the timestamps incorrectly (it's like it's splitting the string at the last colon).  In any event, you can solve this issue by adding xml2js 0.4.4 to your package.json.  This version is parsing the string correctly.

**Comment by isakar** [comment]
Perfect!, I will adding it. Thank you so much for your help.

**Comment by isakar** [comment]
I tried with the xml2js 0.4.4 but still process incorrectly, for now i just disabled it.

**Comment by amaanm** [comment]
I have had the same issues, so I disabled the value preprocessor (described and submitted PR for issue #8 ) which is already merged.
