### ISSUE TITLE
xml to json with array

### ISSUE THREAD

**Issue by Smus** [nmarus/node-ews#30]
Hi, Im trying to get [meeting appointments](https://msdn.microsoft.com/en-us/library/office/dn495614(v=exchg.150).aspx)
But It fails to get the Subject, Start and End form the calendar

### So this
```
<t:AdditionalProperties>
  <t:FieldURI FieldURI="item:Subject" />
  <t:FieldURI FieldURI="calendar:Start" />
  <t:FieldURI FieldURI="calendar:End" />
</t:AdditionalProperties>
```

### becomes: 
```
'AdditionalProperties':{
      "FieldURI": [
         {"FieldURI": "item:Subject"},
         {"FieldURI": "calendar:Start"},
         {"FieldURI": "calendar:End"}
      ]
    }
```
But then it fails to find the FieldURI
a:ErrorSchemaValidation: The request failed schema validation: The required attribute 'FieldURI' is missing.

Any ideas?

**Comment by Smus** [comment]
poke

**Comment by sdim** [comment]
'AdditionalProperties':{
      "FieldURI": [
        { 'attributes': {"FieldURI": "item:Subject"} },
        { 'attributes': {"FieldURI": "calendar:Start"} },
        { 'attributes': {"FieldURI": "calendar:End"} }
      ]
    }

**Comment by Smus** [comment]
That worked! I have been struggling with this for hours!
