### ISSUE TITLE
Basic Auth enable if NTLM doesn't work

### ISSUE THREAD

**Issue by ervinfetic** [nmarus/node-ews#7]
We would appreciate to implement support for basic auth functionality. For example, if we try with ntlm auth and we got and error (i.e. if we setup auth in exchange like on image below we will get an error )

<img width="620" alt="screen shot 2016-06-02 at 17 31 29" src="https://cloud.githubusercontent.com/assets/15788855/15750802/16bbfdd2-28e8-11e6-8405-985af26904e2.png">

then we would like to try basic auth automatically. If credentials are correct just we will continue with the process. Or we wish to implement flag functionality where we can choose which auth we want to use either ntlm or basic auth.

Is it possible and easy to implement these functionalities?

**Comment by nmarus** [comment]
The package currently forces NTLM authentication. If you are looking for similar functionality, check out https://www.npmjs.com/package/soap which this package is uses along with a customized authentication module and some post processing. Might add this a feature at some point in the future, but currently no plans to do that. Feel free to submit a pull request if you are able to add that option.

**Comment by ervinfetic** [comment]
Thanks for the response @nmarus

**Comment by gautamsi** [comment]
I have another cool library for use with Exchange EWS. This is called `ews-javascript-api` and hosted at https://github.com/gautamsi/ews-javascript-api.  This also support basic authentication and cookies authentication along with NTLM.

Most functionality and operations are complete, you can open issues if you find any issues, I am actively working on it.

**Comment by ervinfetic** [comment]
Hi!

Yes I tried that library but I had problem with NTLM auth and I didn't solve this issue. For each my request I'm getting status code 401 - unauthorized and when I try with **node-ews** lib everything is working perfectly. I'm using **XHRApi adapter** as you've described in description but I stuck and I have no idea how to solve this. I will send you more details tomorrow and few screenshots of my source code.

By the way both of these libraries  are awesome  and I'm looking forward to continue with them.

Br.
